#!/bin/bash

#Instruction for use
#1. Create script with name kubectl-*your plugin name*. A plugin is a standalone executable file, whose name begins with kubectl-.
#   You may name it however you want, in my example it calls kubeplugin.
#2. To use a plugin, make the plugin executable: sudo chmod +x ./kubectl-kubeplugin
#3. And place it anywhere in your PATH: sudo mv ./kubectl-kubeplugin /usr/local/bin
#4. You may now invoke your plugin as a kubectl command: kubectl kubeplugin first_argument second_argument
#   where first argument its your desirable resourse type and second argument its namespace name.
#   For example: kubectl kubeplugin pod kube-system

# Define command-line arguments

RESOURCE_TYPE=$1
NAMESPACE=$2

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo "$RESOURCE_TYPE,$NAMESPACE,$NAME,$CPU,$MEMORY"
done
