apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: gcr.io/vsk44-406212/demo:v2.0.0
            command: ["/bin/sh", "-c", "echo Hello from the CronJob"]
          restartPolicy: OnFailure