apiVersion: batch/v1
kind: Job
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        image: gcr.io/vsk44-406212/demo:v2.0.0
        command: ["/bin/sh", "-c", "echo Hello from the Job"]
      restartPolicy: Never