apiVersion: v1
kind: Pod
metadata:
  name: app-multicontainer
spec:
  containers:
  - name: main-container
    image: gcr.io/vsk44-406212/demo:v2.0.0
    ports:
    - containerPort: 8080
  - name: sidecar-container
    image: gcr.io/another-image/demo:v1.0.0
    command: ["/bin/sh", "-c", "echo Hello from the Sidecar"]